# Generated by Django 4.1.4 on 2022-12-28 20:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantor',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
