# Generated by Django 4.1.4 on 2022-12-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursement',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='loan',
        ),
        migrations.DeleteModel(
            name='Defaulter',
        ),
        migrations.DeleteModel(
            name='Disbursement',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
    ]
